# Generated by Django 4.0.8 on 2024-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevents',
            name='posted_as',
            field=models.CharField(choices=[('Новости', 'Новость'), ('События', 'Событие')], max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.CharField(blank=True, choices=[('Первый', 'Первый'), ('Второй', 'Второй'), ('Третий', 'Третий')], max_length=10),
        ),
    ]
