# Generated by Django 4.0.8 on 2024-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='relation_ship',
            field=models.TextField(blank=True, choices=[('Отец', 'Отец'), ('Мать', 'Мать'), ('Брат', 'Брат'), ('Сестра', 'Сестра'), ('Бабушка', 'Бабушка'), ('Дедушка', 'Дедушка'), ('Другое', 'Другое')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('Бакалавр', 'Степень бакалавра'), ('Магистр', 'Степень магистра')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина')], max_length=1, null=True),
        ),
    ]
